# Generated by Django 4.1.2 on 2023-11-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wellness', '0002_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.IntegerField(),
        ),
    ]
